name: Bandit Security Check

on: [push, pull_request]

jobs:
  bandit:
      runs-on: ubuntu-latest
      steps:
              - name heckout code

                    uses actions/checkoutv2

                        - name et up ython

                              uses actions/setup-pythonv2

                                    with

                                            python-version '3.x'



                                                - name nstall dependencies

                                                      run 

                                                              python -m pip install --upgrade pip

                                                                      pip install bandit



                                                                          - name un andit

                                                                                run bandit -r . -f json -o banditoutput.json --severity-level high



                                                                                    - name heck for vulnerabilities

                                                                                          run 

                                                                                                  cat banditoutput.json

                                                                                                          if grep -q 'severity H' banditoutput.json; then
                                                                                                          
                                                                                                                    echo igh severity vulnerabilities found
                                                                                                                    
                                                                                                                              exit 1
                                                                                                                              
                                                                                                                                      else
                                                                                                                                      
                                                                                                                                                echo o high severity vulnerabilities found.
                                                                                                                                                
                                                                                                                                                        fi
                                                                                                                                                        
                                                                                                                                                        
